Output assets/demo.gif
Set Theme "Catppuccin Mocha"
Set FontFamily "MesloLGS NF"
Set FontSize 22
Set Width 1200
Set Height 800
Set Padding 40
Set TypingSpeed 75ms

Type "opvm"
Sleep 500ms
Enter
Sleep 2s

Type "opvm search"
Sleep 500ms
Enter
Sleep 3s

Type "opvm search 1.16.5"
Sleep 500ms
Enter
Sleep 2s

Type "opvm search 1.20.1"
Sleep 500ms
Enter
Sleep 2s

Type "opvm add 1.16.5[1] 1.20.1[~]"
Sleep 1s
Enter
Sleep 4s

Type "opvm list"
Sleep 500ms
Enter
Sleep 2s

Type "opvm remove 1.16.5[~]"
Sleep 500ms
Enter
Sleep 2s

Type "opvm list"
Sleep 500ms
Enter
Sleep 2s

Sleep 1s
Type "exit"
Enter
Sleep 1s
